name: Terraform

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  id-token: write  # Grant permission to use the ID token

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.0.0  # Specify your Terraform version here

      - name: Extract Azure Credentials from Secret
        id: azure-creds
        run: |
          echo "::set-output name=client_id::$(echo '${{ secrets.AZURE_CREDENTIALS }}' | jq -r .clientId)"
          echo "::set-output name=client_secret::$(echo '${{ secrets.AZURE_CREDENTIALS }}' | jq -r .clientSecret)"
          echo "::set-output name=tenant_id::$(echo '${{ secrets.AZURE_CREDENTIALS }}' | jq -r .tenantId)"
        shell: bash

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ steps.azure-creds.outputs.client_id }}        # Use extracted Client ID
          client-secret: ${{ steps.azure-creds.outputs.client_secret }}  # Use extracted Client Secret
          tenant-id: ${{ steps.azure-creds.outputs.tenant_id }}         # Use extracted Tenant ID
          allow-no-subscriptions: true                                  # Allow login without a subscription ID
          auth-type: 'servicePrincipal'                                 # Specify the authentication type

      - name: Terraform Init
        run: terraform init
        working-directory: ./terraform  # Specify the directory containing your Terraform files

      - name: Terraform Validate
        run: terraform validate
        working-directory: ./terraform  # Specify the directory containing your Terraform files

      - name: Terraform Plan
        id: plan
        run: terraform plan -out=tfplan -var-file=terraform.tfvars
        working-directory: ./terraform  # Specify the directory containing your Terraform files

      - name: Terraform Apply
        if: github.ref == 'refs/heads/main'
        run: terraform apply -auto-approve tfplan
        working-directory: ./terraform  # Specify the directory containing your Terraform files
