name: Terraform

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.0.0  # Specify your Terraform version here

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}  # Reference the combined JSON secret for credentials
          allow-no-subscriptions: true  # Allow login without a subscription ID

      - name: Terraform Init
        run: terraform init
        working-directory: ./terraform  # Specify the directory containing your Terraform files

      - name: Terraform Validate
        run: terraform validate
        working-directory: ./terraform  # Specify the directory containing your Terraform files

      - name: Terraform Plan
        id: plan
        run: terraform plan -out=tfplan -var-file=terraform.tfvars
        working-directory: ./terraform  # Specify the directory containing your Terraform files

      - name: Terraform Apply
        if: github.ref == 'refs/heads/main'
        run: terraform apply -auto-approve tfplan
        working-directory: ./terraform  # Specify the directory containing your Terraform files
