name: Terraform

on:
  workflow_dispatch: # This allows manual triggering
    inputs:
      subscription_id:
        description: 'Azure Subscription ID'
        required: true
      client_id:
        description: 'Azure Client ID'
        required: true
      client_secret:
        description: 'Azure Client Secret'
        required: true
      tenant_id:
        description: 'Azure Tenant ID'
        required: true
      location:
        description: 'Azure Location (e.g., North Europe)'
        required: true
      resource_group_name:
        description: 'Name of the Resource Group'
        required: true
      vm_size:
        description: 'Size of the VMs (e.g., Standard_D2as_v5)'
        required: true
      os_disk_size:
        description: 'OS Disk Size in GB'
        required: true
      os_version:
        description: 'Operating System Version (e.g., 2022-Datacenter)'
        required: true
      number_of_vms:
        description: 'Number of VMs to be created'
        required: true

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.3.0  # Specify your Terraform version here

      - name: Terraform Init
        run: terraform init

      - name: Terraform Apply
        run: terraform apply -auto-approve \
          -var="subscription_id=${{ github.event.inputs.subscription_id }}" \
          -var="client_id=${{ github.event.inputs.client_id }}" \
          -var="client_secret=${{ github.event.inputs.client_secret }}" \
          -var="tenant_id=${{ github.event.inputs.tenant_id }}" \
          -var="location=${{ github.event.inputs.location }}" \
          -var="resource_group_name=${{ github.event.inputs.resource_group_name }}" \
          -var="vm_size=${{ github.event.inputs.vm_size }}" \
          -var="os_disk_size=${{ github.event.inputs.os_disk_size }}" \
          -var="os_version=${{ github.event.inputs.os_version }}" \
          -var="number_of_vms=${{ github.event.inputs.number_of_vms }}"
